# 👇 1
events{}

http {
    # 👇 2
    include /etc/nginx/mime.types;
    server {
        # 👇 3
        listen 80;
        # 👇 4
        server_name localhost;
        # 👇 5
        root /usr/share/nginx/html;
        # 👇 6
        index index.html;
        location / {
            # 👇 7
            try_files $uri $uri/ /index.html;
        }
    }
}