services:
  db:
    container_name: db
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - backups:/root/backups
    environment:
      POSTGRES_DB: studo
      POSTGRES_USER: devusr
      POSTGRES_PASSWORD: devpwd
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devusr -d studo"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s

  cache:
    container_name: redis
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: >
      redis-server
      --save 20 1
      --loglevel warning
      --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache_data:/data

  metabase:
    image: metabase/metabase:latest
    ports:
      - "3030:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: ${METABASE_DB_PASS}
      MB_DB_HOST: metabase-db
    depends_on:
      metabase-db:
        condition: service_healthy

  metabase-db:
    image: postgres:16
    environment:
      POSTGRES_DB: metabase
      POSTGRES_USER: metabase
      POSTGRES_PASSWORD: ${METABASE_DB_PASS}
    volumes:
      - metabase-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U metabase -d metabase"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data: {}
  backups: {}
  cache_data: {}
  metabase-data:
