services:
  db-test:
    image: postgres:16-alpine
    ports:
      - '5433:5432' # Mapt interne poort 5432 naar 5433 lokaal
    volumes:
      - db_data_test:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: devusr
      POSTGRES_PASSWORD: devpwd
      POSTGRES_DB: studo_test # De database naam
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U devusr -d studo_test" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  db_data_test: