services:
  db:
    container_name: STUDO
    image: postgres:16
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: studo
      POSTGRES_USER: devusr
      POSTGRES_PASSWORD: devpwd
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U devusr -d studo" ]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s

volumes:
  db_data: