packages:
  - "apps/api-node"
  - "apps/web"
  - "packages/*"
allowBuilds:
  "@firebase/util": false
  "@nestjs/core": false
  "@parcel/watcher": true
  "@scarf/scarf": false
  "@swc/core": false
  argon2: false
  core-js: false
  cpu-features: false
  esbuild: false
  protobufjs: false
  sharp: false
  ssh2: false
  unrs-resolver: false
