//app/layout.tsx
import type {Metadata} from "next";
//TODO
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-expect-error
import "/apps/web/app/globals.css";
import IcoSwitcher from "@/components/ui/overige/ui/IcoSwitcher";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: { children: React.ReactNode; }) {


    return (
        <html lang="en">
        <head>
            <link rel="stylesheet" href="https://use.typekit.net/fmn3jvz.css"/>
            <link rel="preconnect" href="https://fonts.googleapis.com"/>
            <link rel="preconnect" href="https://fonts.gstatic.com"/>
            <IcoSwitcher/>
            <link
                href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
                rel="stylesheet"/>
        </head>

        <body>{children}</body>
        </html>
    );
}