import {
  ArrowDownWideNarrow,
  Calendar,
  CalendarClock,
  ChartNoAxesColumnIncreasing,
  CircleAlert,
  CircleDashed,
  Paperclip,
  TextAlignJustify,
  TextInitial,
} from "lucide-react";

export const COURSE_GRID_TEMPLATE =
  "8rem 1fr 10rem 1fr 10rem 10rem 10rem 10rem 10rem";
export const TableColumns = [
  {
    colId: "statusColumn",
    label: "status",
    icon: CircleDashed,
    rowIndex: 1,
    width: "8rem",
    maxWidth: "15rem",
    minWidth: "8rem",
  },
  {
    colId: "titleColumn",
    label: "title",
    icon: TextAlignJustify,
    rowIndex: 2,
    width: "1fr",
    maxWidth: "40rem",
    minWidth: "20rem",
  },
  {
    colId: "createdAtColumn",
    label: "createdAt",
    icon: Calendar,
    rowIndex: 3,
    width: "10rem",
    maxWidth: "15rem",
    minWidth: "10rem",
  },
  {
    colId: "descriptionColumn",
    label: "description",
    icon: TextInitial,
    rowIndex: 4,
    width: "1fr",
    maxWidth: "50rem",
    minWidth: "25rem",
  },
  {
    colId: "priorityColumn",
    label: "priority",
    icon: ChartNoAxesColumnIncreasing,
    rowIndex: 5,
    width: "10rem",
    maxWidth: "",
    minWidth: "10rem",
  },
  {
    colId: "dueDateColumn",
    label: "dueDate",
    icon: CalendarClock,
    rowIndex: 6,
    width: "10rem",
    maxWidth: "",
    minWidth: "10rem",
  },
  {
    colId: "typeColumn",
    label: "type",
    icon: ArrowDownWideNarrow,
    rowIndex: 7,
    width: "10rem",
    maxWidth: "",
    minWidth: "10rem",
  },
  {
    colId: "resourceColumn",
    label: "resource",
    icon: Paperclip,
    rowIndex: 8,
    width: "10rem",
    maxWidth: "",
    minWidth: "10rem",
  },
  {
    colId: "priorityColumn",
    label: "priority",
    icon: CircleAlert,
    rowIndex: 9,
    width: "10rem",
    maxWidth: "",
    minWidth: "10rem",
  },
];
