include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_final_locals: true
    avoid_redundant_argument_values: true
    unnecessary_lambdas: true
