import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next (app)",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
    const auth: boolean = false;
  return (
    <html lang="en">
      <body
        className={`w-screen h-screen`}
      >
        {children}
      </body>
    </html>
  );
}
