import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";
import ConsoleEasterEgg from "@/components/easteregg/console";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next (app)",
  icons: "/favicon.ico"

};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
    <body
        className={`w-screen h-screen`}
    >
    {children}
      </body>
        <ConsoleEasterEgg/>
    </html>
  );
}
