import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";
import AuthLayout from "@/app/[locale]/(app)/layout";
import MarketingLayout from "@/app/[locale]/(marketing)/layout";
import {NextIntlClientProvider} from "next-intl";
import { getMessages } from "next-intl/server";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next (app)",
};


export default async function RootLayout({
                                             children,
                                             params,
                                         }: {
    children: ReactNode;
    params: { locale: string };
}) {
    const messages = await getMessages();
    const auth: boolean = false;

    return (
        <html lang="en">
            <head>
                <link rel="stylesheet" href="https://use.typekit.net/fmn3jvz.css" />
            </head>
            <NextIntlClientProvider messages={messages}>
                <body className="">
                {children}
                </body>
            </NextIntlClientProvider>
        </html>
    );
}
