[package]
name = "workers"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
aws-config = "1.10.1"
aws-sdk-s3 = "1.141.0"
chrono = "0.4.45"
diesel = { version = "2.3.12", features = ["postgres_backend", "uuid", "chrono", "serde_json"] }
diesel-async = { version = "0.9.2", features = ["postgres", "deadpool"] }
dotenvy = "0.15.7"
pdfium-render = { version = "0.9.3", features = ["thread_safe"] }
pgvector = { version = "0.4.2", features = ["diesel"] }
redis = { version = "1.5.0", features = ["tokio-comp", "connection-manager", "streams"] }
scoped-futures = "0.1.4"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
text-splitter = { version = "0.32.0", features = ["markdown"] }
thiserror = "2.0.20"
tokio = "1.53.1"
tokio-util = { version = "0.7.19", features = ["rt"] }
uuid = "1.24.0"
